### ISSUE TITLE
搜索功能如何配置

### ISSUE THREAD

**Issue by ihxkjggg** [lxchapu/astro-gyoza#1]
你好，看到你的模板很不错。试了下，发现我将appid和APPkey配置好后，还是无法搜索，请问这个要怎么配置才可以呢？可以指导一下吗？

**Comment by lxchapu** [comment]
目前接入的是 DocSearch，你可以前往它的网站 https://docsearch.algolia.com/apply 进行申请，申请通过后会往你的邮箱发送一封邮件，里面包含了对应的 `appId` `apiKey` 和 `indexName`。将它们填写到 config.json 文件的对应配置项即可。

最后非常感谢您的使用，这个模版还处于非常早期的阶段，可能会有各种 Bug，欢迎提建议和PR。后续可能会采用别的搜索集成~~

**Comment by ihxkjggg** [comment]
好的，有问题我反馈，目前都挺好
