### ISSUE TITLE
希望能增加搜索栏的呈现方式

### ISSUE THREAD

**Issue by drowsyindra** [lxchapu/astro-gyoza#13]
很喜欢这个主题！

但感觉现在的搜索栏在这个主题中显得突兀，或许可以试试Astro有的Pagefind，或者其它方式进行站内搜索

**Comment by lxchapu** [comment]
我也觉得不太和谐，只是暂时没有满意的设计。近期我会看看相关的内容。

如果你有好的想法欢迎来提交PR！👏🏻

**Comment by lxchapu** [comment]
目前已经集成了[Pagefind](https://pagefind.app/)
