### ISSUE TITLE
希望可以和shiro一樣提供一個留言板塊

### ISSUE THREAD

**Issue by SliverKeigo** [lxchapu/astro-gyoza#6]
![image](https://github.com/lxchapu/astro-gyoza/assets/112426853/5d386da3-f8ce-48aa-9ba4-f0bc6dcd09ea)

**Comment by lxchapu** [comment]
刚刚，Gyoza 支持了一种~~还算~~简单的方式添加自定义页面，希望可以帮助到您：

1. 在 `src/content/spec` 目录下添加一个 `.md` 文件，它会被渲染成一个页面
2. 修改 `config.json` 的配置项 `menus`，添加你需要的路由

**Comment by SliverKeigo** [comment]
![image](https://github.com/lxchapu/astro-gyoza/assets/112426853/40f56363-f2a3-4842-96b6-ee8a640cfb5f)
爲什麽找不到頁面呢🤔

**Comment by SliverKeigo** [comment]
![image](https://github.com/lxchapu/astro-gyoza/assets/112426853/1eae55d7-39d2-453b-b776-6b526f01e2e5)

**Comment by lxchapu** [comment]
可以提供一个重现该问题的最小示例吗？

**Comment by SliverKeigo** [comment]
我解決了,感謝👋  是我把[spec].astro文件放到了page文件夾的子目錄下,弄錯了位置

**Comment by lxchapu** [comment]
好的☺️
